const API = {
  AbsOSSUrl: 'http://47.103.55.170:28080/sys/aliyun-oss/getSign',
  OSSUrl: '/aliyun-oss/getSign',
  OSSUrlDelete: '/aliyun-oss/deleteObject',
  Login: '/sys-user/login',
  Logout: '/sys-user/logout',
  Welcome: '/welcome',
  SysRolePageList:'/sys-role/pageList',
  SysRoleInsert:'/sys-role/add',
  SysRoleUpdate:'/sys-role/update',
  SysUserPageList:'/sys-user/pageList',
  SysUserInsert:'/sys-user/add',
  SysUserUpdate:'/sys-user/update',
  SysUserDelete:'/sys-user/deleteById',
  SysUserGrabHighSeasClient:'/sys-user/grabHighSeasClient',
  ClientPageList:'/user/pageList',
  SuccessCaseAdd:'/success-case/add',
  SuccessCaseDelete:'/success-case/deleteById',
  SuccessCaseGet:'/success-case/getById',
  SuccessCaseUpdate:'/success-case/update',
  SuccessCasePageList:'/success-case/pageList',
  ProjectAdd:'/project/add',
  ProjectDelete:'/project/deleteById',
  ProjectGet:'/project/getById',
  ProjectUpdate:'/project/update',
  ProjectPageList:'/project/pageList',
  FundAdd:'/fund/add',
  FundDelete:'/fund/deleteById',
  FundGet:'/fund/getById',
  FundUpdate:'/fund/update',
  FundPageList:'/fund/pageList',
  NewsAdd:'/news/add',
  NewsDelete:'/news/deleteById',
  NewsGet:'/news/getById',
  NewsUpdate:'/news/update',
  NewsPageList:'/news/pageList',
  AppointmentProjectPageList:'/appointment-project/pageList',
  FinanceNeedsPageList:'/finance-needs/pageList',
  InvestorAdd:'/investor/add',
  InvestorDelete:'/investor/deleteById',
  InvestorGet:'/investor/getById',
  InvestorUpdate:'/investor/update',
  InvestorPageList:'/investor/pageList',
  InvestOrgAdd:'/invest-org/add',
  InvestOrgDelete:'/invest-org/deleteById',
  InvestOrgGet:'/invest-org/getById',
  InvestOrgUpdate:'/invest-org/update',
  InvestOrgPageList:'/invest-org/pageList',
}

export default API
