const API = {
  OSSUrl: '/aliyun-oss/getSign',
  Login: '/sys-user/login',
  Logout: '/sys-user/logout',
  Welcome: '/welcome',
  SysRolePageList:'/sys-role/pageList',
  SysRoleInsert:'/sys-role/add',
  SysRoleUpdate:'/sys-role/update',
  SysUserPageList:'/sys-user/pageList',
  SysUserInsert:'/sys-user/add',
  SysUserUpdate:'/sys-user/update',
  SysUserDelete:'/sys-user/deleteById',
  ClientPageList:'/user/pageList',
  SuccessCaseAdd:'/success-case/add',
  SuccessCaseDelete:'/success-case/deleteById',
  SuccessCaseGet:'/success-case/getById',
  SuccessCaseUpdate:'/success-case/update',
  SuccessCasePageList:'/success-case/pageList',
  ProjectAdd:'/project/add',
  ProjectDelete:'/project/deleteById',
  ProjectGet:'/project/getById',
  ProjectUpdate:'/project/update',
  ProjectPageList:'/project/pageList',
  FundAdd:'/fund/add',
  FundDelete:'/fund/deleteById',
  FundGet:'/fund/getById',
  FundUpdate:'/fund/update',
  FundPageList:'/fund/pageList',
}

export default API
